### ISSUE TITLE
cusor is kind of dim

### ISSUE THREAD

**Issue by redguardtoo** [alloy-d/color-theme-molokai#3]
some user reported at my site, but looks it's color-theme's issue.
https://github.com/redguardtoo/emacs.d/issues/70

**Comment by IvanMalison** [comment]
hmm I only have this issue in very specific circumstances:

I noticed that I occasionally get a black cursor when using molokai as my emacs startup screen. After fiddling with things a little bit, I was able to isolate the problem. It turns out that it only occurs when molokai is enabled at startup and emacs is run in server/client mode.

Here are steps to reproduce the issue:

1. Put the following elisp in `~/molokai_init.el`:
``` elisp
(setq server-use-tcp t)
(package-initialize)
(load-theme 'molokai t)
```
2. `/usr/local/Cellar/emacs/24.4/Emacs.app/Contents/MacOS/Emacs -q -l ~/Desktop/molokai_init.el --daemon=molokai` (Replace /usr/local/Cellar/emacs/24.4/Emacs.app/Contents/MacOS/Emacs with the path to your emacs binary as necessary)

3. `emacsclient --server-file=molokai -c -n`

**Comment by IvanMalison** [comment]
ping. Any ideas here?

**Comment by redguardtoo** [comment]
cool, thank you.

**Comment by alloy-d** [comment]
@redguardtoo thanks for reporting it! And @IvanMalison, thanks for the detailed steps to reproduce.

Thank you both for your patience, too; I've been out of the Emacs game for a while.
